version: "3.7"

services:
  proyectos-monolitica:
    container_name: proyectos-monolitica
    image: proyectos-monolitica:v1
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - proyectos-app

networks:
  proyectos-app:
